// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuTVQcF7LBRlsON6EL5rOiGY_2yF9O92E',
    appId: '1:348561513167:web:628f18084bcfb9c76ab5ba',
    messagingSenderId: '348561513167',
    projectId: 'denguelens',
    authDomain: 'denguelens.firebaseapp.com',
    storageBucket: 'denguelens.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6hB-E_2ISBPDwsV_Y-uoM6RGKbI6zD6A',
    appId: '1:348561513167:android:51fce3ffef4e99046ab5ba',
    messagingSenderId: '348561513167',
    projectId: 'denguelens',
    storageBucket: 'denguelens.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5UeJVP0AmKzHF-cQAqfAw-wvtDCfkjB8',
    appId: '1:348561513167:ios:40b96fde35c8d88e6ab5ba',
    messagingSenderId: '348561513167',
    projectId: 'denguelens',
    storageBucket: 'denguelens.firebasestorage.app',
    iosBundleId: 'com.example.qwe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5UeJVP0AmKzHF-cQAqfAw-wvtDCfkjB8',
    appId: '1:348561513167:ios:40b96fde35c8d88e6ab5ba',
    messagingSenderId: '348561513167',
    projectId: 'denguelens',
    storageBucket: 'denguelens.firebasestorage.app',
    iosBundleId: 'com.example.qwe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuTVQcF7LBRlsON6EL5rOiGY_2yF9O92E',
    appId: '1:348561513167:web:5e89187a094b1eb16ab5ba',
    messagingSenderId: '348561513167',
    projectId: 'denguelens',
    authDomain: 'denguelens.firebaseapp.com',
    storageBucket: 'denguelens.firebasestorage.app',
  );
}
